### ISSUE TITLE
Import error:  'GEOHAYSTACK'

### ISSUE THREAD

**Issue by AnimusXCASH** [lixxu/sanic-motor#15]
Hey,

i wanted to try the framework with pymongo however I got this issue:

```Traceback (most recent call last):
  File "D:\Coding\Trader_server\app.py", line 7, in <module>
    from sanic_motor import BaseModel
  File "D:\Coding\Trader_server\traderEnv\lib\site-packages\sanic_motor\__init__.py", line 7, in <module>
    from pymongo import (
ImportError: cannot import name 'GEOHAYSTACK' from 'pymongo' (D:\Coding\Trader_server\traderEnv\lib\site-packages\pymongo\__init__.py)
```

Code has been copied from the repo example. 

Current installed package versions are:

```Package       Version
------------- -------
aiofiles      22.1.0
dnspython     2.2.1
httptools     0.5.0
motor         3.1.1
multidict     6.0.3
pip           22.3.1
pymongo       4.3.3
sanic         22.9.1
sanic-motor   0.6.0
sanic-routing 22.8.0
setuptools    65.5.1
websockets    10.4
wheel         0.38.4
```

any help please?

thank you for your time and answer

**Comment by lixxu** [comment]
Sorry, the updated code was not uploaded to pypi. 0.7.0 was uploaded just now. Please try this new version.

**Comment by AnimusXCASH** [comment]
Thank you
