### ISSUE TITLE
TypeError: MotorDatabase object is not callable  with motor==2.0.0

### ISSUE THREAD

**Issue by autogestion** [lixxu/sanic-motor#4]
Full traceback
```
[2018-08-15 21:45:40 +0300] [26229] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/envs/pgate/lib/python3.6/site-packages/sanic/app.py", line 646, in run
    serve(**server_settings)
  File "/home/envs/pgate/lib/python3.6/site-packages/sanic/server.py", line 588, in serve
    trigger_events(before_start, loop)
  File "/home/envs/pgate/lib/python3.6/site-packages/sanic/server.py", line 496, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1422, in uvloop.loop.Loop.run_until_complete
  File "/home/envs/pgate/lib/python3.6/site-packages/sanic_motor/__init__.py", line 89, in open_connection
    BaseModel.default_open_connection(app, loop, name, uri)
  File "/home/envs/pgate/lib/python3.6/site-packages/sanic_motor/__init__.py", line 103, in default_open_connection
    db = client.get_default_database()
  File "/home/envs/pgate/lib/python3.6/site-packages/motor/core.py", line 460, in __call__
    database_name, client_class_name))
TypeError: MotorDatabase object is not callable. If you meant to call the 'get_default_database' method on a AsyncIOMotorClient object it is failing because no such method exists.
Traceback (most recent call last):
  File "/snap/pycharm-professional/80/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/snap/pycharm-professional/80/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/snap/pycharm-professional/80/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/80/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/pubgate/run_api.py", line 7, in <module>
    app.run(host="0.0.0.0", port=8000)
  File "/home/envs/pgate/lib/python3.6/site-packages/sanic/app.py", line 646, in run
    serve(**server_settings)
  File "/home/envs/pgate/lib/python3.6/site-packages/sanic/server.py", line 588, in serve
    trigger_events(before_start, loop)
  File "/home/envs/pgate/lib/python3.6/site-packages/sanic/server.py", line 496, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1422, in uvloop.loop.Loop.run_until_complete
  File "/home/envs/pgate/lib/python3.6/site-packages/sanic_motor/__init__.py", line 89, in open_connection
    BaseModel.default_open_connection(app, loop, name, uri)
  File "/home/envs/pgate/lib/python3.6/site-packages/sanic_motor/__init__.py", line 103, in default_open_connection
    db = client.get_default_database()
  File "/home/envs/pgate/lib/python3.6/site-packages/motor/core.py", line 460, in __call__
    database_name, client_class_name))
TypeError: MotorDatabase object is not callable. If you meant to call the 'get_default_database' method on a AsyncIOMotorClient object it is failing because no such method exists.
sys:1: RuntimeWarning: coroutine 'register_admin' was never awaited
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
```
If switch back to motor==1.2.2 and pymongo==3.6.1 , works correctly

**Comment by lixxu** [comment]
upgrade to latest sanic-motor to try.

**Comment by autogestion** [comment]
yep, problem fixed

**Comment by lixxu** [comment]
closing as problem fixed.
