### ISSUE TITLE
Python3.7 pip install fails - latest version (0.3.2)

### ISSUE THREAD

**Issue by colinben** [lixxu/sanic-motor#5]
`Collecting sanic-motor
  Using cached https://files.pythonhosted.org/packages/ab/02/fc722087268ee5a62778b3c381a8cb0bf4f3f655452629810a57a7f2a47e/sanic-motor-0.3.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "/private/var/folders/t8/cx90qfnj1bz73tr_1fsj6rzw0000gn/T/pip-install-7n_ronkj/sanic-motor/sanic_motor/__init__.py", line 5, in <module>
        from sanic.log import logger
    ModuleNotFoundError: No module named 'sanic'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/t8/cx90qfnj1bz73tr_1fsj6rzw0000gn/T/pip-install-7n_ronkj/sanic-motor/setup.py", line 9, in <module>
        import sanic_motor
      File "/private/var/folders/t8/cx90qfnj1bz73tr_1fsj6rzw0000gn/T/pip-install-7n_ronkj/sanic-motor/sanic_motor/__init__.py", line 7, in <module>
        from sanic.log import log as logger
    ModuleNotFoundError: No module named 'sanic'
`

**Comment by lixxu** [comment]
sorry, the way to collect the version is not correct, pls try again.

**Comment by lixxu** [comment]
issue fixed.
