### ISSUE TITLE
Travis fails when trying to install 0.3.3

### ISSUE THREAD

**Issue by xen** [lixxu/sanic-motor#6]
I have `sanic_motor` dependency on the development requirements for `sanic_session` and with the latest version it fails to build because of error `setup.py`. The full log is available by the link:
https://travis-ci.org/xen/sanic_session/jobs/421046411. 

Traceback:

```
https://files.pythonhosted.org/packages/3f/12/de495223524a2eaca52fdb6b13e8f5bacbd9bbac67711aa8e1c9a4007559/sanic-motor-0.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-95qurk4c/sanic-motor/setup.py", line 15, in <module>
        with p.open(encoding='utf-8') as f:
      File "/opt/python/3.5.6/lib/python3.5/pathlib.py", line 1151, in open
        opener=self._opener)
      File "/opt/python/3.5.6/lib/python3.5/pathlib.py", line 1005, in _opener
        return self._accessor.open(self, flags, mode)
      File "/opt/python/3.5.6/lib/python3.5/pathlib.py", line 371, in wrapped
        return strfunc(str(pathobj), *args)
    NotADirectoryError: [Errno 20] Not a directory: '/tmp/pip-install-95qurk4c/sanic-motor/setup.py/../sanic_motor/__init__.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-95qurk4c/sanic-motor/
```

**Comment by lixxu** [comment]
seems caused by the relative path, changed to abspath. please try again.

**Comment by lixxu** [comment]
closing due to long time no response.
